#!/usr/bin/env python3

import sys
import datetime
import dateutil

def newdate(a,s):
    return a + dateutil.relativedelta.relativedelta(seconds=int(s))

default_start = datetime.datetime(1979,8,1,0,0,0)
default_timestep = 150

if len(sys.argv) < 2:
    print('Usage: {} XXX'.format(sys.argv[0]))
    sys.exit(-1)
request = int(sys.argv[1])
print('Request       : '+str(request))
print('Reference date: '+str(default_start))
print('Timestep      : '+str(default_timestep))
result_time = newdate(default_start,request)
result_pickup = newdate(default_start,request*default_timestep)
print('Result if time   : '+str(result_time))
print('Result if pickup : '+str(result_pickup))
